openapi: 3.0.0
info:
  title: BioNLP-ST Evaluation API
  description: API to access evaluation for SeeDev and BB tasks of BioNLP-OST 2019
  version: 0.0.1

servers:
  - url: http://127.0.0.1:8080/bionlp-st-web/api
    description: local Maven-Jetty server
  - url: http://bibliome.jouy.inra.fr/demo/BioNLP-ST-2016-Evaluation/api
    description: official server with evaluation on test data
    
paths:
  /list-tasks:
    get:
      summary: Returns the list of supported tasks
      operationId: listTasks
      responses:
        '200':
          description: OK
          
  /task/{taskName}/{set}/check:
    post:
      summary: Checks the correctness of a submission given as a zip archive
      operationId: checkSubmission
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                zipfile:
                  type: string
                  format: binary
                  description: Zip archive containing the predictions
              required: [ zipfile ]
      parameters:
        - $ref: "#/components/parameters/TaskName"
        - $ref: "#/components/parameters/DocumentSet"
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                
  /task/{taskName}/{set}/evaluate:
    post:
      summary: Evaluates a submission given as a zip archive
      operationId: evaluateSubmission
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                zipfile:
                  type: string
                  format: binary
                  description: Zip archive containing the predictions
                resamples:
                  type: integer
                  description: If specified, computes the confidence interval with bootstrap resampling
                  example: 0
                detailed:
                  type: boolean
                  description: If true, shows pairings and errors (only for sets train and dev)
                  example: false
                alternate:
                  type: boolean
                  description: If false, computes only the first scoring
                  example: true
              required: [ zipfile ]
      parameters:
        - $ref: "#/components/parameters/TaskName"
        - $ref: "#/components/parameters/DocumentSet"
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
          
components:
  parameters:
    TaskName:
      name: taskName
      in: path
      required: true
      description: task identifier
      schema:
        type: string
        enum: [SeeDev-full, SeeDev-binary, BB19-norm, BB19-rel, BB19-kb, BB19-norm+ner, BB19-rel+ner, BB19-kb+ner, BB-cat, BB-event, BB-kb, BB-cat+ner, BB-event+ner, BB-kb+ner, BioCreative5-CDR ]

    DocumentSet:
      name: set
      in: path
      required: true
      description: document set
      schema:
        type: string
        enum: [ train, dev, test ]
